apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:
  gce-pd-csi-driver
resources:
- ../../base/controller
- ../../base/node_linux
patchesStrategicMerge:
- no_snapshotter_sidecar.yaml
- no_snapshotter_roles.yaml
- no_win_roles.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: csi-gce-pd-controller
  path: metrics_leaderelection_endpoint.yaml
transformers:
- ../../images/stable-1-16
