# for external-provisioner
- op: replace
  path: /spec/template/spec/containers/0/args/3
  value: "--metrics-address=:22011"
- op: replace
  path: /spec/template/spec/containers/0/args/7
  value: "--enable-leader-election"
- op: replace
  path: /spec/template/spec/containers/0/args/8
  value: "--leader-election-type=leases"
- op: remove
  path: /spec/template/spec/containers/0/ports
- op: remove
  path: /spec/template/spec/containers/0/livenessProbe
# for external-attacher
- op: replace
  path: /spec/template/spec/containers/1/args/2
  value: "--metrics-address=:22012"
- op: remove
  path: /spec/template/spec/containers/1/ports
- op: remove
  path: /spec/template/spec/containers/1/livenessProbe
# for external-resizer
- op: replace
  path: /spec/template/spec/containers/2/args/2
  value: "--metrics-address=:22013"
- op: remove
  path: /spec/template/spec/containers/2/ports
- op: remove
  path: /spec/template/spec/containers/2/livenessProbe
