apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../alpha
patches:
- controller_always_pull.yaml
- node_always_pull.yaml
namespace:
  gce-pd-csi-driver
transformers:
- ../../images/dev

