kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node-win
spec:
  template:
    spec:
      containers:
        - name: csi-driver-registrar
          # introduced in node-driver-registrar v2.3.0
          livenessProbe:
            $patch: delete
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node
spec:
  template:
    spec:
      containers:
        - name: csi-driver-registrar
          # introduced in node-driver-registrar v2.3.0
          livenessProbe:
            $patch: delete
