# Increase operation timeout for provisioner sidecar.
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "--timeout=250s"
# Increase operation timeout for attacher sidecar.
- op: add
  path: /spec/template/spec/containers/1/args/-
  value: "--timeout=250s"
# Increase operation timeout for snapshotter sidecar.
- op: add
  path: /spec/template/spec/containers/3/args/-
  value: "--timeout=300s"
