kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: restore-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-gce-pd
  resources:
    requests:
      storage: 6Gi
  dataSource:
    kind: VolumeSnapshot
    name: demo-snapshot-podpvc
    apiGroup: snapshot.storage.k8s.io
