apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: csi-gce-pd
provisioner: csi-gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
volumeBindingMode: Immediate
