apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: REPLACEME/gcp-compute-persistent-disk-csi-driver
  newName: gcr.io/gke-release-staging/gcp-compute-persistent-disk-csi-driver
  newTag: "latest"
- name: REPLACEME/csi-provisioner
  newName: gcr.io/gke-release-staging/csi-provisioner
  newTag: "latest"
- name: REPLACEME/csi-attacher
  newName: gcr.io/gke-release-staging/csi-attacher
  newTag: "latest"
- name: REPLACEME/csi-node-driver-registrar
  newName: gcr.io/gke-release-staging/csi-node-driver-registrar
  newTag: "latest"
