apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-provisioner
imageTag:
  name: gke.gcr.io/csi-provisioner
  newTag: "v1.6.0-gke.0"

---
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-attacher
imageTag:
  name: gke.gcr.io/csi-attacher
  newTag: "v2.2.0-gke.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-resizer
imageTag:
  name: gke.gcr.io/csi-resizer
  newTag: "v0.5.0-gke.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-snapshotter
imageTag:
  name: gke.gcr.io/csi-snapshotter
  newTag: "v2.1.1-gke.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-csi-node-registrar
imageTag:
  name: gke.gcr.io/csi-node-driver-registrar
  newTag: "v1.3.0-gke.0"
---

apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-gcepd-driver
imageTag:
  name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  # Don't change stable image without changing pdImagePlaceholder in
  # test/k8s-integration/main.go
  newTag: "v0.7.0-gke.0"
---
